version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: COPIiwXcVZuyBVltIjtYhYCUnqyJSRwp
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: COPIiwXcVZuyBVltIjtYhYCUnqyJSRwp
    ports:
      - "3306:3306"
