version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql.railway.internal
      - DB_PORT=3306
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=COPIiwXcZuyBVltIjtYhYCUnqyJSRwp
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: COPIiwXcZuyBVltIjtYhYCUnqyJSRwp
    ports:
      - "3306:3306"
