version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: laravel-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: my_database
      DB_USERNAME: root
      DB_PASSWORD: root_password

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: COPIiwXcVZuyBVltIjtYhYCUnqyJSRwp
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: COPIiwXcVZuyBVltIjtYhYCUnqyJSRwp
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
